package com.what3words.addressvalidator.javawrapper.addresslookupservice.loqate.network.dto

import com.squareup.moshi.Json

internal data class RetrieveItemDTO(
    @Json(name = "Id") val id: String?,
    @Json(name = "DomesticId") val domesticId: String?,
    @Json(name = "Language") val language: String?,
    @Json(name = "LanguageAlternatives") val languageAlternatives: String?,
    @Json(name = "Department") val department: String?,
    @Json(name = "Company") val company: String?,
    @Json(name = "SubBuilding") val subBuilding: String?,
    @Json(name = "BuildingNumber") val buildingNumber: String?,
    @Json(name = "BuildingName") val buildingName: String?,
    @Json(name = "SecondaryStreet") val secondaryStreet: String?,
    @Json(name = "Street") val street: String?,
    @Json(name = "Block") val block: String?,
    @Json(name = "Neighbourhood") val neighbourhood: String?,
    @Json(name = "District") val district: String?,
    @Json(name = "City") val city: String?,
    @Json(name = "Line1") val line1: String?,
    @Json(name = "Line2") val line2: String?,
    @Json(name = "Line3") val line3: String?,
    @Json(name = "Line4") val line4: String?,
    @Json(name = "Line5") val line5: String?,
    @Json(name = "AdminAreaName") val adminAreaName: String?,
    @Json(name = "AdminAreaCode") val adminAreaCode: String?,
    @Json(name = "Province") val province: String?,
    @Json(name = "ProvinceName") val provinceName: String?,
    @Json(name = "ProvinceCode") val provinceCode: String?,
    @Json(name = "PostalCode") val postalCode: String?,
    @Json(name = "CountryName") val countryName: String?,
    @Json(name = "CountryIso2") val countryIso2: String?,
    @Json(name = "CountryIso3") val countryIso3: String?,
    @Json(name = "CountryIsoNumber") val countryIsoNumber: String?,
    @Json(name = "SortingNumber1") val sortingNumber1: String?,
    @Json(name = "SortingNumber2") val sortingNumber2: String?,
    @Json(name = "Barcode") val barcode: String?,
    @Json(name = "POBoxNumber") val poBoxNumber: String?,
    @Json(name = "Label") val label: String?,
    @Json(name = "Type") val type: String?,
    @Json(name = "DataLevel") val dataLevel: String?,
    @Json(name = "Field1") val field1: String?,
    @Json(name = "Field2") val field2: String?,
    @Json(name = "Field3") val field3: String?,
    @Json(name = "Field4") val field4: String?,
    @Json(name = "Field5") val field5: String?,
    @Json(name = "Field6") val field6: String?,
    @Json(name = "Field7") val field7: String?,
    @Json(name = "Field8") val field8: String?,
    @Json(name = "Field9") val field9: String?,
    @Json(name = "Field10") val field10: String?,
    @Json(name = "Field11") val field11: String?,
    @Json(name = "Field12") val field12: String?,
    @Json(name = "Field13") val field13: String?,
    @Json(name = "Field14") val field14: String?,
    @Json(name = "Field15") val field15: String?,
    @Json(name = "Field16") val field16: String?,
    @Json(name = "Field17") val field17: String?,
    @Json(name = "Field18") val field18: String?,
    @Json(name = "Field19") val field19: String?,
    @Json(name = "Field20") val field20: String?
)
